server:
  port: 8881

neo4j:
  driver: org.neo4j.ogm.drivers.http.driver.HttpDriver
  user: neo4j
  password: root
  uri: http://localhost:7474

google:
  apiKey: AIzaSyBAHZ3gLdePXcY1GbHpQM3PEfAGwLB3lyA

zeromq:
  topic:
    findRoutes:
      envelope: FIND_ROUTES_TASK
      address: tcp://*:5563
      ioThreads: 1
    saveRoutes:
      envelope: SAVE_ROUTES_TASK
      address: tcp://*:5564
      ioThreads: 1

redis:
  host: localhost
  port: 6379